Session-Value für 'rex_syslog_last_seen' setzen
FriendsOfREDAXO/minibar pull request #68
Opened 2020-08-09 08:41 UTC by christophboecker

Setzt beim Besuch der Syslog-Seite den Session-Value, so dass Besuche der Seite erkannt und die Syslog-Flagge grün oder gelb wird. #53

2020-08-29 07:02 UTC, staabm commented
danke für den PR. hab versucht den fix zu vereinfachen. @skerbis @christophboecker kannst du das nochmal gegentesten.

kann gemerged werden, wenn es noch funktioniert.

2020-08-29 07:03 UTC, staabm approved these changes

2020-08-29 07:22 UTC, staabm commented
gerne neues release machen wenn gemerged

2020-08-29 10:49 UTC, skerbis requested changes
Irgendwie bleibt bei mir im Frontend die Flagge gelb, während sie im Backend grün wird. 

<img width="397" alt="Bildschirmfoto 2020-08-29 um 12 52 50" src="https://user-images.githubusercontent.com/791247/91635188-9f2d6380-e9f6-11ea-924b-b7e3cb2f3659.png">
<img width="495" alt="Bildschirmfoto 2020-08-29 um 12 52 38" src="https://user-images.githubusercontent.com/791247/91635189-a0f72700-e9f6-11ea-9771-702b2c427438.png">

2020-08-29 10:53 UTC, staabm commented
Das liegt daran das frontend und backend eigene sessions haben

2020-08-29 14:17 UTC, christophboecker commented
Also müssten beide Sessions den Gelesen-Status erhalten. Da, wenn ich es richtig verstehe, `rex_set_session` automatisch die Session auswählt (was also aufgrund der vorherigen Abfrage die BE-Session ist), muss die FE-Session "manuell" befüllt werden:
``` php
class rex_minibar_element_syslog extends rex_minibar_element
{

    public function __construct()
    {
        if (rex::isBackend() && rex_be_controller::getCurrentPage() == 'system/log/redaxo') {
                $filetime = filemtime(rex_logger::getPath());
                rex_set_session('rex_syslog_last_seen', $filetime );
                $_SESSION[rex::getProperty('instname')]['rex_syslog_last_seen'] = $filetime;
        }
    }
```
Ob das reicht kann ich nicht beurteilen; kenne mich damit nicht weiter aus. Evtl muss man noch Fragen ob die Session existiert oder so?

2020-08-29 15:53 UTC, staabm commented
@gharlan hast du ne bessere idee?

2020-08-29 15:54 UTC, staabm commented
Oder @bloep vllt?

2020-08-29 19:07 UTC, bloep commented
ggf. anstatt zwei Sessions zu füllen, auch im Frontend auf die Backend-Session zugreifen?

2020-08-29 19:43 UTC, christophboecker commented
Damit verlagerst Du das Problem nur. Statt bei den relativ wenigen Schreibvorgänge wird bei jedem FE-Seitenaufruf am vorgesehenen Weg vorbeigearbeitet. Am Ende ist es aber m.E. egal. So oder so muss der vorgesehene Weg umgangen werden. Oder man baut rex_request so um, dass zwischen den Sessions gewählt werden kann.

2020-08-30 09:17 UTC, staabm commented
> ggf. anstatt zwei Sessions zu füllen, auch im Frontend auf die Backend-Session zugreifen?

Ich glaube das ist ne gute idee.

2020-08-30 09:35 UTC, christophboecker commented
Ich möchte jetzt nicht unnötig ein Grundsatzfass aufmachen, aber zumindest mal anfragen ob die Diskussion lohnt.  ... beim direkten Zugriff mittels $_SESSION geht ja die durch rex_request::session eingebaute Absicherung und Kapselung verloren. Bei Funktionen wie rex_session bin ich mir nicht sicher, ob sie Relikte aus alter Zeit sind und man vieleicht mal hier und da den Umstieg auf rex_request angehen sollte?

Wäre es sinnvoll, folgendes anzugehen:
1. Hier ersteinmal - egal ob links oder rechts herum, ihr seid kundiger was sinnvoller ist - mit direktem $_SESSION-Zugriff die "andere" Session abzufragen oder zu befüllen; bei der Gelegenheit von rex_session auf rex_request::session etc. umstellen.
2. rex_request so zu erweitern, dass man die Ziel-Session auswählen kann; um einen BC zu vermeiden ist der Default immer "wie heute".
3. Dann noch mal hier anpassen auf die neuen Möglichkeiten in rex_request?

Änderung in rex_request ungefähr so: neuer Parameter $target. Wenn der null ist (default, nicht angegeben), wird getSessionNamespace wie gehabt rex::isBackend abfragen. Ist $target TRUE wird die BE-Session genomen, ist $target FALSE wird die FE-Session genommen. So in der Art ... hier mal ein Beispiel:
```php
public static function setSession($varname, $value, $target = null)
{
    if (PHP_SESSION_ACTIVE != session_status()) {
        throw new rex_exception('Session not started, call rex_login::startSession() before!');
    }
    $_SESSION[self::getSessionNamespace($target)][$varname] = $value;
}
```

2020-08-30 13:34 UTC, staabm commented
@skerbis @christophboecker habs jetzt noch angepasst und es sollte passen für fronten/backend.

bitte erneut testen, bei mir hats gepasst.

2020-08-30 13:35 UTC, staabm commented
> Ich möchte jetzt nicht unnötig ein Grundsatzfass aufmachen, aber zumindest mal anfragen ob die Diskussion lohnt. ... beim direkten Zugriff mittels $_SESSION geht ja die durch rex_request::session eingebaute Absicherung und Kapselung verloren. Bei Funktionen wie rex_session bin ich mir nicht sicher, ob sie Relikte aus alter Zeit sind und man vieleicht mal hier und da den Umstieg auf rex_request angehen sollte?

ich denke mit dem stand aus dem PR - wenn sich herausstellt dass es funktioniert - kann man erstmal leben.
man muss selten über kreuz mit session arbeiten wie hier, daher seh ich erstmal wenig bedarf hier was zu überarbeiten

2020-08-30 18:53 UTC, skerbis approved these changes
LGTM - tested

2020-08-30 18:53 UTC, merged

2020-08-30 18:57 UTC, staabm commented
Super dnake. Gerne ein neues release fertig machen. 😘